from typing import Callable, List, Tuple
import numpy as np
from abc import ABC, abstractmethod

class EvolutionaryAlgorithm(ABC):
    """
    Abstract base class defining the standard architecture for population-based 
    evolutionary algorithms and metaheuristics.

    This class enforces a uniform interface across different optimization strategies,
    ensuring that all derived algorithms share common initialization protocols,
    state tracking, and execution signatures. This standardization is critical 
    for executing rigorous statistical benchmarking over continuous search spaces.
    """

    def __init__(self, objective_function: Callable, bounds: List, population_size: int = 50, max_iterations: int = 100) -> None:
        """
        Initializes the fundamental hyperparameters and state variables required 
        for the optimization process.

        Args:
            objective_function (callable): The mathematical function to be minimized.
            bounds (list of tuples or numpy.ndarray): The continuous search domain 
                                                      defined as [lower_bound, upper_bound] 
                                                      for each dimension.
            population_size (int): The number of candidate solutions evaluated per generation.
            max_iterations (int): The termination criterion defining the maximum 
                                  number of evolutionary cycles.
        """
        self.objective_function = objective_function
        
        # Array conversion ensures vectorized operations can be applied efficiently 
        # during mutation or boundary handling
        self.bounds = np.array(bounds)
        self.population_size = population_size
        self.max_iterations = max_iterations
        
        # The dimensionality of the problem is implicitly derived from the bounds matrix
        self.dimension = len(self.bounds)
        
        # State trackers required to store the global optimum throughout the execution
        self.best_individual = None
        self.best_fitness = float('inf')
        
        # Convergence tracker used to store the best fitness value of each generation,
        # which is later utilized to generate convergence plots and statistical analysis
        self.fitness_history = []

    def _initialize_population(self) -> np.ndarray:
        """
        Generates the initial set of candidate solutions.

        The initial population is generated by sampling from a uniform probability 
        distribution bounded by the defined search space. This ensures an unbiased 
        exploration of the domain during the first generation.

        Returns:
            numpy.ndarray: A matrix of shape (population_size, dimension) containing 
                           the initial candidate vectors.
        """
        # Vectorized extraction of the lower and upper limits for the search space
        lower_bounds = self.bounds[:, 0]
        upper_bounds = self.bounds[:, 1]
        
        # Matrix generation using uniform sampling across all dimensions simultaneously
        initial_population = np.random.uniform(
            low=lower_bounds, 
            high=upper_bounds, 
            size=(self.population_size, self.dimension)
        )
        
        return initial_population

    @abstractmethod
    def run(self) -> Tuple[np.ndarray, float]:
        """
        Executes the core evolutionary loop.

        This method acts as the main algorithmic contract. Every subclass must implement 
        its own stochastic search mechanisms, position updates, or probabilistic models 
        within this function. 

        Returns:
            tuple: A pair containing the best candidate vector (numpy.ndarray) and 
                   its corresponding fitness value (float).
        """
        pass